global using crud.Models;
global using Microsoft.AspNetCore.Authentication.JwtBearer;
global using Microsoft.AspNetCore.Authorization;
global using Microsoft.IdentityModel.Tokens;
global using Microsoft.OpenApi.Models;
global using System.Text;
global using Microsoft.EntityFrameworkCore;
global using System.IdentityModel.Tokens.Jwt;
global using System.Security.Claims;
